### ISSUE TITLE
An action to just install Liquibase

### ISSUE THREAD

**Issue by alexeyinkin** [liquibase/github-action-generator#119]
I would like an action that just installs Liquibase so that I can run commands in subsequent steps. The current actions are inconvenient for me because:

- I have a mono-repo, and my configuration is under `liquibase` directory, and locally I run my commands in that directory. When a current action runs, I can't override the working directory, and so my calls on the local machine and a GitHub workflow differ substantially.
- I have all my properties in `liquibase.properties` file so that locally I can just run `liquibase update`. However, the current `update` action requires me to have `changelogFile` parameter. This is a duplication as I already have it in my `liquibase.properties`.
- I need to install Google Cloud Spanner plugin. I put it into `liquibase/liquibase_lib`, and it's found automatically when I run commands in `liquibase` directory. With current actions, it can't find the plugin because the working directory is different. So I must fiddle with `classpath` parameter as in #77 

This substantial complexity will go away entirely if I could just have

```yaml
- uses: liquibase-github-actions/install@v4.27.0

- run: |
    cd liquibase
    liquibase update
```

**Comment by jnewton03** [comment]
hi @alexeyinkin, for your use case I would recommend using the liquibase docker container instead of the default actions.  The docker container allows you to setup custom workflows.  You could do something like this:
```
jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:4.27.0

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Liquibase Update
      working-directory: ./liquibase
      run: |
        liquibase update
```
