### ISSUE TITLE
Add GHCR option for containers built in each action

### ISSUE THREAD

**Issue by asheliahut** [liquibase/github-action-generator#151]
I am running my GitHub actions from self hosted runners for my enterprise. We are consistently running into issues with dockerhub rate limits, and forcing people to login to our artifactory and so forth in order to build containers. Where we can we prefer to not have to do so and run everything from within GitHub actions and not have to call out to artifactory to proxy to dockerhub.

Due to pull limits for dockerhub, is it possible to add a GitHub Container Registry option of the docker containers used so that when pulling occurs it uses GitHub Actions auth to pull the containers.

Another option would be to add an action that just simply downloads liquibase and sets it up for use via cli just like the other issue mentioned before that was closed: #119 

As of today we just have to download the binary and set up our environment ourselves, but it would be nice to not have to do all that custom code.

**Comment by jnewton03** [comment]
hi @asheliahut , sorry for the delay.  I'm trying to understand your request a bit better.  The GitHub Actions aren't really customizable, so we tend to steer people towards using the docker container directly.  Are you requesting we push the liquibase docker container to both Docker Hub and GHCR?  Our Image is official in Docker Hub.  Thanks!

**Comment by asheliahut** [comment]
Hey @jnewton03 Yes the request is to push to both, that way many users who run into rate limits due to Docker Hub having very strict limits can easily continue to use the container actions without having to add more login steps. At scale with many jobs running on self-hosted infrastructure for GitHub Actions eventually causes rate limiting to occur. 

The same solution I was looking for here is similar to how the dflook terraform actions work. For example of what they now suggest for people to get around that issue: [Dflook Docker Hub Rate Limit Exceeded](https://github.com/dflook/terraform-github-actions/discussions/330)

**Comment by asheliahut** [comment]
@jnewton03 that rate limits mentioned there is based on pushing up containers with a reused token. 

The rate limit should barely ever be reached in GitHub actions due to every run having access to a fresh GITHUB_TOKEN with access to pull. 

Yes I understand the ability to override and use artifactory is an option, it is what I do today, but for people who don't necessarily have that problem but still run into this could increase especially considering dockerhub recent increased their rate limiting further to 10 pulls per hour for unauthenticated. Just adding this option would open up many more pull options with less thinking for users.

**Comment by jnewton03** [comment]
@asheliahut that makes sense.  The first step on our side is publishing the docker image itself to GHCR.  Working on that here: https://github.com/liquibase/docker/pull/379

**Comment by jnewton03** [comment]
@asheliahut sorry for the delay on this.  We've pre-released an initial version of a `setup-liquibase` action here: https://github.com/liquibase/setup-liquibase/releases/tag/v1-beta that I believe is what you are looking for.  Would love for you to be one of our initial testers.  Thanks for being a valued member of the community!

**Comment by Server4001** [comment]
Hello @jnewton03 I am seeing the following error with using a self-hosted runner on GitHub Cloud:

```
Run liquibase/setup-liquibase@v1-beta
  with:
    version: 4.32.0
    edition: oss
    cache: false
Setting up Liquibase version 4.32.0 (oss edition)
Installing Liquibase oss version 4.32.0
Downloading from: https://package.liquibase.com/downloads/cli/liquibase/releases/download/v4.32.0/liquibase-4.32.0.tar.gz
/usr/bin/tar xzf /runner/_work/_temp/02bb7415-c42e-4634-84af-072436f06d85 -C /tmp/liquibase-extract-1e34meu9e5i
Error: Failed to validate Liquibase installation: The process '/tmp/liquibase-extract-1e34meu9e5i/liquibase' failed with exit code 1
```

Here is what the GHA config looks like:

```
name: Test Setup Liquibase Beta

on:
  workflow_dispatch:
  push:
    branches: [my-branch-name-here]

jobs:
  test-basic:
    runs-on: [self-hosted, Standard, ubuntu, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Liquibase OSS
        uses: liquibase/setup-liquibase@v1-beta
        with:
          version: '4.32.0'
          edition: 'oss'
          cache: false

      - name: Verify Installation
        run: |
          liquibase --version
          which liquibase
```
