### ISSUE TITLE
There is no option to send liquibase properties as input

### ISSUE THREAD

**Issue by himanshu9891** [liquibase/github-action-generator#66]
Similar to below liquibase cli command, there must be an option to include defaultFile in this action.

liquibase --defaultsFile=<custom.liquibase.properties>

**Comment by mcred** [comment]
All of the generated commands in https://github.com/liquibase-github-actions have the global parameters which include `defaults_file`. Example update:
```
steps:
  - uses: actions/checkout@v3
  - uses: liquibase-github-actions/update@v4.19.1
    with:
      ...
      defaultsFile: ""
      ...
```
